config/routes.rb
Rails.application.routes.draw do
  namespace :casein do
    resources :events
  end

  root 'application#index'

  resources :events, only: [:index, :show]

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from StandardError do |exception|
    logger.error exception.message
    fail exception
  end

  def index
    render text: 'temporary route'
  end
end

app/controllers/casein/events_controller.rb
# Scaffolding generated by Casein v5.1.1.5

module Casein
  class EventsController < Casein::CaseinController
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = 'Events'
      @events = Event.order(sort_order(:type)).paginate page: params[:page]
    end

    def show
      @casein_page_title = 'View event'
      @event = Event.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new event'
      @event = Event.new
    end

    def create
      @event = Event.new event_params

      if @event.save
        flash[:notice] = 'Event created'
        redirect_to casein_events_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new event'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update event'

      @event = Event.find params[:id]

      if @event.update_attributes event_params
        flash[:notice] = 'Event has been updated'
        redirect_to casein_events_path
      else
        flash.now[:warning] = 'There were problems when trying to update this event'
        render action: :show
      end
    end

    def destroy
      @event = Event.find params[:id]

      @event.destroy
      flash[:notice] = 'Event has been deleted'
      redirect_to casein_events_path
    end

    private

    def event_params
      params.require(:event).permit(
        :type, :start_date, :end_date, :description, :is_published, :recap_url,
        :home_team_a, :home_team_b, :visiting_team_a, :visiting_team_b, :ticket_url
      )
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.paginate(page: params[:page])
  end

  def show
    @event = Event.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casein/config_helper.rb
module Casein
  module ConfigHelper
    # Name of website or client: used throughout Casein.
    def casein_config_website_name
      'Casein'
    end

    # Filename of logo image. Ideally, it should be a transparent PNG around 140x30px
    def casein_config_logo
      'casein/casein.png'
    end

    # The server hostname where Casein will run
    def casein_config_hostname
      if Rails.env.production?
        'http://www.caseincms.com'
      else
        'http://0.0.0.0:3000'
      end
    end

    # The sender address used for email notifications
    def casein_config_email_from_address
      'donotreply@caseincms.com'
    end

    # The initial page the user is shown after they sign in or click the logo. Probably
    # this should be set to the first tab.
    # Do not point this at casein/index!
    def casein_config_dashboard_url
      url_for controller: :events, action: :index
    end

    # A list of stylesheets to include. Do not remove the core casein/casein,
    # but you can change the load order, if required.
    def casein_config_stylesheet_includes
      %w(casein/casein casein/custom)
    end

    # A list of JavaScript files to include. Do not remove the core casein/casein, but you
    #  can change the load order, if required.
    def casein_config_javascript_includes
      %w(casein/casein casein/custom)
    end
  end
end

app/views/casein/events/_form.html.slim
= tinymce_assets
.row
  .col-lg-4
    = casein_text_field f, f.object, :type
  .col-lg-4
    = casein_date_select f, f.object, :start_date
  .col-lg-4
    = casein_date_select f, f.object, :end_date
.row
  .col-lg-12
    = casein_text_area f, f.object, :description, class: 'tinymce'
.row
  .col-lg-6
    = casein_text_field f, f.object, :home_team_a, casein_label: 'Home team A'
  .col-lg-6
    = casein_text_field f, f.object, :home_team_b, casein_label: 'Home team B'
.row
  .col-lg-6
    = casein_text_field f, f.object, :visiting_team_a, casein_label: 'Visiting team A'
  .col-lg-6
    = casein_text_field f, f.object, :visiting_team_b, casein_label: 'Visiting team B'
.row
  .col-lg-6
    = casein_text_field f, f.object, :recap_url
  .col-lg-6
    = casein_text_field f, f.object, :ticket_url
.row
  .col-lg-6
.row
  .col-lg-2.col-lg-offset-10
    = casein_select f, f.object, :is_published, ['Draft', 'Published'], casein_label: 'Published?'
= tinymce

app/views/casein/events/_table.html.slim
table.table.table-striped.table-hover.table-condensed
  thead
    tr
      th
        = casein_sort_link "Type", :type
      th
        = casein_sort_link "Start date", :start_date
      th
        = casein_sort_link "End date", :end_date
      th
        = casein_sort_link "Description", :description
      th
        = casein_sort_link "Is published", :is_published
      th
        = casein_sort_link "Recap url", :recap_url
      th
        = casein_sort_link "Home team a", :home_team_a
      th
        = casein_sort_link "Home team b", :home_team_b
      th
        = casein_sort_link "Visiting team a", :visiting_team_a
      th
        = casein_sort_link "Visiting team b", :visiting_team_b
      th
        = casein_sort_link "Ticket url", :ticket_url
      th
        |  
  - events.each do |event|
    tr
      td
        = casein_table_cell_link event.type, casein_event_path(event)
      td
        = casein_table_cell_link event.start_date, casein_event_path(event)
      td
        = casein_table_cell_link event.end_date, casein_event_path(event)
      td
        = casein_table_cell_link event.description, casein_event_path(event)
      td
        = casein_table_cell_link event.is_published, casein_event_path(event)
      td
        = casein_table_cell_link event.recap_url, casein_event_path(event)
      td
        = casein_table_cell_link event.home_team_a, casein_event_path(event)
      td
        = casein_table_cell_link event.home_team_b, casein_event_path(event)
      td
        = casein_table_cell_link event.visiting_team_a, casein_event_path(event)
      td
        = casein_table_cell_link event.visiting_team_b, casein_event_path(event)
      td
        = casein_table_cell_link event.ticket_url, casein_event_path(event)
      td.delete
        = link_to(casein_show_row_icon("trash"), casein_event_path(event), :method => :delete, :data => { :confirm => "Are you sure you want to delete this event?" })

app/views/casein/events/index.html.slim
h2
  | Events
  = casein_pagination_details @events
= render :partial => 'casein/events/table', :locals => { :events => @events }
.text-center
  = will_paginate @events
= content_for :sidebar do
  li
    = link_to "#{casein_show_icon "plus-sign"}Add a new event".html_safe, new_casein_event_path

app/views/casein/events/new.html.slim
h2
  | Add a new event
= form_for @event, :url => casein_events_path do |f|
  = render :partial => 'casein/events/form', :locals => { :f => f }
  p.submits
    = link_to 'Cancel', casein_events_path, :class => 'btn btn-mini btn-danger'
    = f.submit "Add new event", :class => "btn btn-mini btn-primary"
= content_for :sidebar do
  li
    = link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_events_path

app/views/casein/events/show.html.slim
h2
  | View event
= form_for @event, :url => casein_event_path(@event) do |f|
  = render :partial => 'casein/events/form', :locals => { :f => f }
  p.submits
    = link_to 'Cancel', casein_events_path, :class => 'btn btn-mini btn-danger'
    = f.submit "Save changes", :class => "btn btn-mini btn-primary"
= content_for :sidebar do
  li
    = link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_events_path

app/views/casein/layouts/_tab_navigation.html.erb
<!-- NOTE: the casein:scaffold generator automatically appends new controllers to this file. The SCAFFOLD_INSERT line must NOT be removed -->
<!-- SCAFFOLD_INSERT -->
<li id="tab-events"><%= link_to "Events", casein_events_path %></li>

app/views/casein/layouts/_tab_navigation.html.slim
li#tab-events
  = link_to "Events", casein_events_path

app/views/casein/layouts/_top_navigation.html.erb
<!-- NOTE: add "hidden-xs hidden-sm" class to li elements you want to be hidden at small browser widths -->
<!-- e.g. <li class="hidden-xs hidden-sm"><%= link_to "Visit site", casein_config_hostname, :target => "_blank" %></li> -->

<li><%= link_to "Visit site", casein_config_hostname, :target => "_blank" %></li>

app/views/casein/layouts/_top_navigation.html.slim
li
  = link_to "Visit site", casein_config_hostname, :target => "_blank"

app/views/events/_item.html.slim
.event
  .date
    | date:
    span.date = event.start_date
  .description == event.description
  .teams
    .match.first
      .team.home: .name = event.home_team_b
      .team.away: .name = event.visiting_team_b
    .match.second
      .team.home: .name = event.home_team_a
      .team.away: .name = event.visiting_team_a

  - unless event.recap_url.empty?
    .recap: a href= event.recap_url Recap
  - unless event.ticket_url.empty?
    .tickets: a href=event.ticket_url Buy tickets

app/views/events/_list.html.slim
.list.events
  - events.each do |event|
    = render partial: 'events/item', locals: { event: event }

app/views/events/index.html.slim
h2
  | Upcoming NRG Events!
= render partial: 'events/list', locals: { events: @events }

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Nrg
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = yield